#-----------------------------------------------
#Config that does not have impact on performance
#-----------------------------------------------


random_seed: 0b011011

#-----------------------------------------------
#1. Dataset
#-----------------------------------------------

dataset:

#directory that have every dataset in it.
  # data_dir: "/media/youngwon/Neo/NeoChoi/Research/CodecEnhancement/CSE+BWE/Dataset/CSE+BWE_dataset"
  data_dir: "/media/zeroone"

  nb_train: "downsampled/train"
  nb_test: "downsampled/test"

  wb_train: "target/train"
  wb_test: "target/test"

#So for this case, wideband test dataset should be located at "/media/zeroone/target/test"

  batch_size: 16
  seg_len: 2
  
  num_workers: 16
 
#-----------------------------------------------
#2. Model
#-----------------------------------------------

#No information

#-----------------------------------------------
#3. Loss
#-----------------------------------------------



#-----------------------------------------------
#4. Optimizer (ADAM)
#-----------------------------------------------

optim:
  learning_rate1: 0.0001
  learning_rate2: 0.00001

  B1: 0.9
  B2: 0.999


#-----------------------------------------------
#Training
#-----------------------------------------------

train:
  normalize: False

  val_step: 20000

  
#Path of output of validation. 
  output_dir_path: "/media/zeroone/output"
  logger_path: "/media/zeroone/logger"

