#-----------------------------------------------
#Config that does not have impact on performance
#-----------------------------------------------

random_seed: 0b011011

#-----------------------------------------------
#1. Dataset
#-----------------------------------------------

dataset:

#directory that have every dataset in it.
  train_dataset_path: ""
  val_dataset_path: ""
  test_dataset_path: ""

  image_size: 96
  batch_size: 16
  num_workers: 16
 
#-----------------------------------------------
#2. Model
#-----------------------------------------------

#No information

#-----------------------------------------------
#3. Loss
#-----------------------------------------------

loss:
  lambda_image: 1
  lambda_adv : 0.001
  lambda_content : 0.006
  lambda_tv: 0.00000002


#-----------------------------------------------
#4. Optimizer (ADAM)
#-----------------------------------------------

optim:
  learning_rate: 0.0001 #before 100000 step


  B1: 0.9
  B2: 0.999


#-----------------------------------------------
#Training
#-----------------------------------------------

train:
  val_epoch: 20
  total_step: 400000 #Due to the existence of two optimizers, a total_step of 400,000 is equivalent to 200,000 actual steps.

  
#Path of output of validation. 
  output_dir_path: "./output"
  logger_path: "./logger"

